### ISSUE TITLE
Java doesn't like "-" class names

### ISSUE THREAD

**Issue by Grimmello** [Atticus29/makeJavaProj#5]
When you give a parameter with a hyphonated name, it messes with the java files and wont let you compile. Maybe add a second parameter for java file name and class name?

**Comment by Atticus29** [comment]
Not a bad idea. Do hyphens work when the parameter begins with a capital letter?

**Comment by Grimmello** [comment]
No, it is the hyphen it doeant like. It is expecting the { symbol, any
other symbol wont let it compile

**Comment by slaughtr** [comment]
Fixed in newest merge
